server:
  port: 8080
  
spring:
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    show-sql: true
    hibernate: 
      ddl-auto: update
  datasource:
    url: jdbc:h2:file:~/h2
    username: as
    password: 
    driverClassName: org.h2.Driver
  jackson:
    serialization:
      fail-on-empty-beans: false